# Generated by Django 5.2.8 on 2025-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments_link_payments_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
