name: CI/CD

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: Install dependencies from cache
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-tests-dependencies-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.poetry-cache.outputs.cache-hit != 'true'
      - name: Setup project
        run: poetry install
      - name: Run tests
        run: python manage.py test

#      - name: Install Poetry
#        run: pip install poetry
#
#      - name: Install dependencies
#        run: pip install --upgrade pip && pip install poetry --no-root&&poetry config virtualenvs.create false
#
#        # Копируем файлы зависимостей
#        COPY pyproject.toml poetry.lock* ./

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/drflessons
            git pull origin develop
            docker compose down
            docker compose up -d --build

